/**
 * English for the academy catalogue, keyed by the Bangla line as written in
 * the page. A line not listed here shows in Bangla, so pages can be added one
 * at a time. `{0}`, `{1}` mark where a number or a link goes (see Tx).
 */
export const EN: Record<string, string> = {
  // The bar and its menus
  "কাণ্ডারী": "Kandari",
  "তৈরি একাডেমি": "Build Academy",
  "কাণ্ডারী তৈরি একাডেমি — প্রথম পাতা": "Kandari Build Academy — home",
  "একাডেমি": "Academies",
  "বিভাগ": "Departments",
  "কোর্স": "Courses",
  "ক্লাস ভিডিও": "Class videos",
  "আমার শেখা": "My learning",
  "শেখান": "Teach",
  "ক্যাটালগ": "Catalogue",
  "দেশের পেশাদারদের ছোট বিশ্ববিদ্যালয়": "Little universities of the country's professionals",
  "প্রতিটি দক্ষতার নিজের ঘর": "A home for every skill",
  "চল্লিশ দিনের হাতে-কলমে কোর্স": "Forty-day, hands-on courses",
  "প্রতি সপ্তাহের বিনামূল্যের ক্লাস": "A free class every week",
  "রুটিন": "Routine",
  "কবে, কখন আপনার ক্লাস": "When your classes are",
  "ক্লাসরুম": "Classroom",
  "লাইভ ক্লাস, রেকর্ডিং আর হোমওয়ার্ক": "Live classes, recordings and homework",
  "পরীক্ষা": "Exam",
  "নিজের প্রজেক্ট আর প্যানেল": "Your project and the panel",
  "সমাবর্তন": "Graduation",
  "সনদ আর প্রকাশ্য বোর্ড": "Certificate and the public board",
  "একাডেমি খুলুন": "Open an academy",
  "নিজের নামে, বা বন্ধুদের নিয়ে": "In your own name, or with friends",
  "ক্লাসরুম খুলুন": "Open a classroom",
  "কোর্সের নতুন ব্যাচ": "A new batch of a course",
  "প্যানেল মার্কিং": "Panel marking",
  "শেষ প্রজেক্টের নম্বর": "Marks for the final project",
  "ভর্তি হোন": "Enrol",
  "ঝুড়ি": "Basket",
  "কোর্সের ঝুড়ি": "Course basket",
  "একাডেমি থেকে বের হন": "Leave the academy",
  "বের হন": "Exit",
  "মেনু খুলুন": "Open menu",
  "মেনু বন্ধ করুন": "Close menu",
  "আলো থিমে যান": "Switch to light theme",
  "অন্ধকার থিমে যান": "Switch to dark theme",

  // The classroom ticker
  "স্বাগতম": "Welcome",
  "ক্লাস কার্যক্রম": "Class activity",
  "ল্যাব": "Lab",
  "গবেষণা": "Research",
  "জমা বাকি": "Due",
  "জমা": "Submitted",
  "ক্লাসের সময়": "Class time",
  "উল্লেখ": "Mention",
  "ক্লাসরুমে সময়": "Time in class",
  "চল্ চল্ চল্। চল্ চল্ চল্। ঊর্ধ্ব গগনে বাজে মাদল": "March on, march on, march on! In the high sky the drum beats",
  "কাগজ এগিয়ে রাখো বন্ধু": "Keep the paper ahead of you, friend",
  "কাজ জমালে জ্বিনে ধরবে": "Let work pile up and the jinn will get you",
  "কষ্ট না করলে কেষ্ট মেলে না।": "No pain, no gain.",
  "একবার না পারিলে দেখ শতবার।": "If you fail once, try a hundred times.",
  "সময় গেলে সাধন হবে না": "Once time is gone, the work won't get done",

  // The classroom hero
  "ক্লাস শিক্ষক": "Class teacher",
  "ব্যাচ লিডার": "Batch leader",
  "আপনি": "You",
  "ব্যাচ {0}": "Batch {0}",
  "লাইভ ক্লাস শুরু করুন": "Start the live class",
  "লাইভ ক্লাসে যোগ দিন": "Join the live class",

  // The classroom dashboard
  "ড্যাশবোর্ড": "Dashboard",
  "নোটিশ বোর্ড": "Notice board",
  "আজ বোর্ড ফাঁকা — কোনো নোটিশ নেই।": "The board is empty today — no notices.",
  "পরীক্ষা ও লিডার": "Exams & leader",
  "পরীক্ষার নাম": "Exam name",
  "দিন": "Day",
  "পূর্ণমান": "Full marks",
  "পরীক্ষা যোগ করুন": "Add exam",
  "পরীক্ষা মুছুন": "Delete exam",
  "এখনো কোনো পরীক্ষা নেই।": "No exams yet.",
  "আপনার নম্বর": "Your marks",
  "ক্লাসের গড়": "Class average",
  "হয়ে গেছে": "Done",
  "আজ": "Today",
  "পরের পরীক্ষা": "Next exam",
  "নোট ও ফাইল": "Notes & files",
  "ক্লাসের নোট ও ফাইল": "Class notes & files",
  "ফাইল দিন": "Share a file",
  "নামান": "Download",
  "সব": "All",
  "ছবি": "Images",
  "ভিডিও": "Videos",
  "অডিও": "Audio",
  "পিডিএফ": "PDF",
  "স্লাইড": "Slides",
  "অন্যান্য": "Other",
  "এখনো কোনো ফাইল নেই — ছবি, ভিডিও, স্লাইড বা পিডিএফ দিয়ে শুরু করুন।": "No files yet — start with a picture, video, slides or a PDF.",
  "টি ফাইল": "files",
  "মাইন্ড ম্যাপ": "Mind map",
  "কোর্সের সপ্তাহগুলো আর আপনার নিজের পরিকল্পনা এক ম্যাপে। সপ্তাহে চাপ দিলে পাঠ খুলবে।": "The course's weeks and your own plan on one map. Press a week to open its lesson.",
  "কোন সপ্তাহে": "Which week",
  "আমার পরিকল্পনা": "My plan",
  "যোগ করুন": "Add",
  "খেলা ও কুইজ": "Play & quiz",
  "পয়েন্ট": "points",
  "দিনের ধারা": "day streak",
  "নতুন প্রশ্ন": "New question",
  "প্রশ্ন যোগ করুন": "Add question",
  "প্রথম প্রশ্নটা লিখুন — ব্যাচ খেলতে শুরু করবে।": "Write the first question — the batch will start playing.",
  "শিক্ষক এখনো কোনো প্রশ্ন দেননি।": "The teacher has not set any question yet.",
  "প্রথম উত্তর": "First answer",
  "৫০ পয়েন্ট": "50 points",
  "টানা তিন দিন": "Three days in a row",
  "টানা সাত দিন": "Seven days in a row",
  "পাঠ ও ফাইল": "Lessons & files",
  "ব্যাচের আড্ডা": "Batch chat",
  "ক্লাস নিয়েছেন": "Classes taken",
  "এই সপ্তাহের পাঠ": "This week's lesson",
  "হাজিরা": "Attendance",
  "উপকরণ": "Materials",
  "আয়": "Earnings",
  "কোর্সের অগ্রগতি": "Course progress",
  "{0}টি ক্লাসের {1}টি": "{1} of {0} classes",
  "ক্লাস করেছেন": "Attended",
  "সামনে আছে": "Ahead",
  "মিস হয়েছে": "Missed",
  "ক্লাসের": "of classes",
  "স্বাগতম, {0}": "Welcome, {0}",
  "আপনার ক্লাসের সব কিছু এক জায়গায় — পরের ক্লাস, রেকর্ডিং, ব্যাচের আড্ডা আর সপ্তাহের কাজ।": "Everything for your class in one place — the next class, recordings, the batch chat and the week's work.",
  "সামনের ক্লাস": "Upcoming classes",
  "ক্লাসের সপ্তাহ শেষ — এখন প্রজেক্ট আর প্যানেল।": "The class weeks are over — now the project and the panel.",
  "সপ্তাহের অগ্রগতি": "Weekly progress",
  "সপ্তাহ {0}": "Week {0}",
  "করেছেন": "Done",
  "এই সপ্তাহ": "This week",
  "মিস": "Missed",
  "সামনে": "Ahead",

  // Share row
  "শেয়ার": "Share",
  "লিংক কপি": "Copy link",
  "কপি হয়েছে": "Copied",
  "ফেসবুক": "Facebook",
  "হোয়াটসঅ্যাপ": "WhatsApp",

  // Levels and kinds
  "শুরু থেকে": "Beginner",
  "মাঝারি": "Intermediate",
  "অভিজ্ঞ": "Advanced",
  "একক একাডেমি": "Solo academy",
  "দলীয় একাডেমি": "Team academy",
  "এক বা একাধিক বিভাগ": "One or more departments",
  "শূন্য থেকে — আগে কিছু জানা লাগে না।": "From zero — no prior knowledge needed.",
  "হাতে কিছু কাজ আছে — এবার পেশাদারের মতো।": "You have some work behind you — now like a professional.",
  "পেশায় আছেন — বড় কাজ, কঠিন সমস্যা।": "Already working — bigger jobs, harder problems.",

  // Academies page
  "{0}টি একাডেমি। দক্ষ হাতের {1}।": "{0} academies. A {1} of skilled hands.",
  "বিশ্ববিদ্যালয়": "university",
  "গ্যারেজের মিস্ত্রি, রাঁধুনি, স্থপতি, তাঁতি, গায়িকা, কোচ — দেশের পেশাদাররা নিজের নামে বা বন্ধুদের নিয়ে একাডেমি খুলেছেন। একাডেমিতে ঢুকে দেখুন কারা শেখান, কীভাবে শেখান, কোন কোন বিভাগ আছে।":
    "Garage mechanics, cooks, architects, weavers, singers, coaches — the country's professionals have opened academies in their own name or with friends. Step inside to see who teaches, how they teach and which departments they run.",
  "সব বিভাগ দেখুন": "See all departments",
  "সব কোর্স দেখুন": "See all courses",
  "সব একাডেমি": "All academies",
  "একাডেমিতে ঢুকে বিভাগ আর কোর্স দেখুন": "Step inside to see departments and courses",
  "একাডেমির ধরন": "Kinds of academy",
  "একক বা দলীয়": "Solo or team",
  "এরপর বিভাগ": "Next: departments",
  "একজন পেশাদারের নামে — তিনিই সব ক্লাস নেন। এক ব্যাচে বড়জোর {0} জন, তাই প্রত্যেকে শিক্ষকের চোখের সামনে।":
    "In one professional's name — they take every class. At most {0} in a batch, so everyone stays under the teacher's eye.",
  "কয়েকজন বন্ধু বা সহকর্মী মিলে — প্রত্যেকে নিজের ভাগটা পড়ান। এক ব্যাচে বড়জোর {0} জন।":
    "A few friends or colleagues together — each teaches their own part. At most {0} in a batch.",
  "বিশ্ববিদ্যালয়ের মতো একাডেমিও কয়েকটা বিভাগ খুলতে পারে। প্রতিটি বিভাগে ঠিক {0}টি কোর্স।":
    "Like a university, an academy can open several departments. Every department has exactly {0} courses.",
  "একজনের নামে, বা {0} মিলে।": "In one person's name, or {0} together.",
  "বন্ধুরা": "friends",
  "ধরন যেটাই হোক, শেখা চলে একই নিয়মে — শুধু ব্যাচের মাপ আলাদা।": "Whichever kind, learning follows the same rules — only the batch size differs.",
  "একাডেমি → বিভাগ → কোর্স": "Academy → Department → Course",
  "একাডেমি দেখলেন, এবার {0}।": "You have seen the academies — now the {0}.",
  "প্রতিটি বিভাগ একটা দক্ষতার ঘর — সব একাডেমির বিভাগ পাশাপাশি দেখে নিজের পথটা ধরুন।": "Every department is a home for one skill — see them side by side and pick your path.",
  "বিভাগে চলুন": "Go to departments",
  "এরপর": "Next",
  "আপনার একাডেমি {0}?": "When is {0} academy?",
  "কবে": "your",
  "কোনো কাজে হাত পাকা? নিজের নামে, বা বন্ধুদের নিয়ে একাডেমি খুলুন — প্রথম বিভাগ চালু হবে আপনার হাতেই।": "Skilled at something? Open an academy in your own name, or with friends — the first department starts in your hands.",

  // Departments page
  "{0}টি বিভাগ · {1}টি একাডেমি · {2}টি কোর্স": "{0} departments · {1} academies · {2} courses",
  "{0}টি বিভাগ। আপনার একটাই {1}।": "{0} departments. Just one {1} for you.",
  "পথ": "path",
  "কোড আর যন্ত্র, বাড়ির নকশা, গ্যারেজ আর রান্নাঘর, গান, রং আর তাঁত, ক্যামেরা, হিসাব, সাজ, মাঠ আর অঙ্ক। দেশের {0}টি একাডেমির সব বিভাগ এক জায়গায় — মনের মতোটায় ঢুকে কোর্স দেখুন।":
    "Code and machines, house design, garages and kitchens, music, colour and loom, camera, accounts, beauty, field and numbers. Every department of the country's {0} academies in one place — step into the one you like and see its courses.",
  "একাডেমিগুলো দেখুন": "See the academies",
  "সব বিভাগে একই": "The same in every department",
  "নিয়ম": "Rules",
  "বিভাগে ঢুকে কোর্স দেখুন": "Step inside to see courses",
  "আরও বিভাগ {0}।": "More departments {0}.",
  "আসছে": "coming",
  "কোনো কাজে আপনার হাত পাকা? নিজের নামে বা বন্ধুদের নিয়ে একাডেমি খুলুন — প্রথম বিভাগ চালু হবে আপনার হাতেই।": "Skilled at something? Open an academy in your own name or with friends — the first department starts in your hands.",
  "শেখার নিয়ম {0} এক।": "The rules of learning are the same {0}.",
  "সবখানে": "everywhere",
  "যে বিভাগেই পড়ুন, শেখা চলে একই নিয়মে। ভর্তির আগেই জেনে নিন কী পাচ্ছেন।": "Whichever department you study in, learning follows the same rules. Know what you get before you enrol.",
  "ঠিক {0}টি কোর্স": "Exactly {0} courses",
  "প্রতিটি বিভাগে তিনটি কোর্স, স্তর লেখা থাকে — শুরু থেকে, মাঝারি বা অভিজ্ঞ। যেখানে আছেন, সেখান থেকে ধরুন।": "Three courses in every department, each with its level — beginner, intermediate or advanced. Start from where you are.",
  "{0} দিনে শেষ": "Done in {0} days",
  "{0} সপ্তাহ ক্লাস, তারপর {1} দিন নিজের প্রজেক্ট আর প্যানেল। বছরের পর বছর নয়।": "{0} weeks of classes, then {1} days for your own project and the panel. Not years on end.",
  "ছোট ব্যাচ": "Small batches",
  "একক একাডেমিতে এক ব্যাচে বড়জোর {0} জন, দলীয় একাডেমিতে {1} জন — প্রত্যেকে শিক্ষকের চোখের সামনে।": "At most {0} in a batch at a solo academy and {1} at a team academy — everyone under the teacher's eye.",
  "{0} মিনিটের লাইভ ক্লাস": "{0}-minute live classes",
  "সপ্তাহে একটা, রুটিনে ঠিক করা দিনে আর সময়ে। না ধরতে পারলে রেকর্ডিং আছে, হোমওয়ার্ক জমা ক্লাসরুমেই।": "One a week, on the day and time set in the routine. Miss it and there is a recording; homework goes in right in the classroom.",
  "টাকা এসক্রোতে": "Money in escrow",
  "প্রতিটি ক্লাস হলে সেই সপ্তাহের ভাগ শিক্ষক পান; ক্লাস না হলে সেই ভাগ আপনার কাছে ফেরত আসে।": "The teacher gets that week's share once the class is held; if it is not, the share comes back to you.",
  "যাচাইযোগ্য সনদ": "Verifiable certificate",
  "খাতার পরীক্ষা নয় — নিজের হাতের প্রজেক্ট আর দুই পরীক্ষকের প্যানেল। পাস করলে সনদের আইডি, নাম ওঠে প্রকাশ্য বোর্ডে।": "Not a paper exam — your own project and a panel of two examiners. Pass, and your certificate ID and name go on the public board.",
  "বিভাগ দেখলেন, এবার {0}।": "You have seen the departments — now the {0}.",
  "সব বিভাগের সব কোর্স পাশাপাশি — নিজের স্তর মিলিয়ে দেখুন, তারপর ভর্তি। কোনটা আপনার, বুঝতে না পারলে প্রথম পাতার তিন প্রশ্নের উত্তর দিন।": "Every course of every department side by side — match your level, then enrol. Not sure which is yours? Answer the three questions on the first page.",
  "কোর্সে চলুন": "Go to courses",
  "এরপর কোর্স": "Next: courses",

  // Courses page
  "{0}টি কোর্স · {1}টি বিভাগ · {2}টি একাডেমি": "{0} courses · {1} departments · {2} academies",
  "{0}টি কোর্স। নিজের {1} শুরু।": "{0} courses. Start at your own {1}.",
  "স্তরে": "level",
  "প্রতিটি কোর্স {0} দিনের — {1} সপ্তাহ ক্লাস, তারপর নিজের প্রজেক্ট আর প্যানেল। সব একাডেমির সব কোর্স এখানে, বিভাগ ধরে সাজানো। স্তর বেছে নিলে আপনারগুলো আলাদা হয়ে উঠবে।":
    "Every course is {0} days — {1} weeks of classes, then your own project and the panel. Every course of every academy is here, arranged by department. Pick your level and yours will stand out.",
  "স্তর মিলিয়ে দেখুন": "Match your level",
  "সব কোর্স": "All courses",
  "বিভাগ ধরে সাজানো, প্রতিটি বিভাগে তিনটি": "Arranged by department, three in each",
  "স্তর": "Levels",
  "প্রতিটি কোর্সে স্তর লেখা থাকে": "Every course states its level",
  "তিন {0}, একই নিয়ম।": "Three {0}s, one set of rules.",
  "যেখানে আছেন, সেখান থেকে ধরুন। এক বিভাগের তিনটি কোর্স একটার পর একটা নিলে পুরো দক্ষতা গড়ে ওঠে।": "Start from where you are. Take a department's three courses one after another and the whole skill takes shape.",
  "{0}টি কোর্স": "{0} courses",
  "চল্লিশ দিন": "Forty days",
  "প্রতিটি কোর্স একই ছন্দে": "Every course keeps the same rhythm",
  "{0} দিন, {1} ছন্দ।": "{0} days, {1} rhythm.",
  "একটাই": "one",
  "যে কোর্সই নিন, শুরু থেকে সমাবর্তন পর্যন্ত পথটা এক। বছরের পর বছর নয় — দেড় মাসেরও কম।": "Whichever course you take, the road from start to graduation is the same. Not years — under a month and a half.",
  "দিন {0}": "Day {0}",
  "{0} মিনিটের লাইভ ক্লাস, সঙ্গে বাড়ির কাজ।": "A {0}-minute live class, with homework.",
  "ক্লাস, বাড়ির কাজ, আর শিক্ষকের মন্তব্য।": "Class, homework, and the teacher's comments.",
  "প্রজেক্ট ও প্যানেল": "Project and panel",
  "{0} দিনে নিজের হাতে ফাইনাল প্রজেক্ট, তারপর দুই পরীক্ষকের প্যানেল।": "{0} days for your own final project, then a panel of two examiners.",
  "পাস করলে যাচাইযোগ্য সনদ, নাম ওঠে প্রকাশ্য বোর্ডে।": "Pass and get a verifiable certificate; your name goes on the public board.",
  "শুরু করুন": "Get started",
  "কোর্স → ভর্তি → ক্লাস": "Course → Enrolment → Class",
  "কোর্স দেখলেন, এবার {0}।": "You have seen the courses — now {0}.",
  "ভর্তি": "enrolment",
  "পছন্দের কোর্সে ঢুকে “ভর্তি হোন” চাপুন — এক ফর্মে নাম, মোবাইল, ব্যাচ আর পেমেন্ট। ফি থাকে এসক্রোতে, ক্লাস হলে তবেই শিক্ষক পান।": "Open the course you like and press “Enrol” — name, mobile, batch and payment in one form. The fee sits in escrow; the teacher is paid only when the class is held.",
  "নিজের কোর্স {0}।": "{0} your own course.",
  "খুলুন": "Open",
  "যে কাজ আপনি ভালো পারেন, সেটা {0} দিনের কোর্সে সাজিয়ে পড়ান — নিজের নামে বা বন্ধুদের নিয়ে একাডেমি খুলে।": "Whatever you do well, teach it as a {0}-day course — by opening an academy in your own name or with friends.",
  "ভর্তির ফর্ম": "Enrolment form",
  "আপনি কোথায় আছেন?": "Where are you?",
  "{0} স্তরে {1}টি কোর্স": "{1} courses at {0} level",
  "সব মিলিয়ে {0}টি কোর্স": "{0} courses in all",
  "কোর্সের নাম": "Course name",
  "আপনার স্তর": "Your level",

  // Cards
  "খুব মিলেছে": "Great match",
  "মিলেছে": "Match",
  "{0} বিভাগ": "{0} department",
  "{0} দেখুন": "See {0}",
  "নতুন ব্যাচ শিগগির": "New batch soon",
  "ব্যাচ চলছে · আসন খালি": "Batch running · seats open",
  "ব্যাচ চলছে · {0}টি আসন": "Batch running · {0} seats",
  "পরের ব্যাচ {0}": "Next batch {0}",
  "বিনা ফি": "Free",
  "বিনা ফি থেকে শুরু": "From free",
  "{0} থেকে": "From {0}",
  "{0} গ্র্যাজুয়েট": "{0} graduates",
  "একাডেমি দেখুন": "See academy",
  "কোর্স দেখুন": "See course",
  "হাতে-কলমে ক্লাস": "Hands-on classes",

  // Academies
  "ষড়বিংশ একাডেমি": "Shorobingsho Academy",
  "তানভীর রহমান স্থাপত্য একাডেমি": "Tanvir Rahman Architecture Academy",
  "রফিকুল মোটরস গ্যারেজ একাডেমি": "Rafiqul Motors Garage Academy",
  "হাঁড়ি-ডেকচি রান্না একাডেমি": "Hari-Dekchi Cooking Academy",
  "মিতু সরকার সংগীত একাডেমি": "Mitu Sarkar Music Academy",
  "সাদমান বিন আহমেদ মিউজিক একাডেমি": "Sadman bin Ahmed Music Academy",
  "জয় চক্রবর্তী আর্ট স্টুডিও": "Joy Chakraborty Art Studio",
  "রূপগঞ্জ কারুশিল্প একাডেমি": "Rupganj Crafts Academy",
  "ফ্রেম স্টুডিও একাডেমি": "Frame Studio Academy",
  "খাতা-কলম ব্যবসা একাডেমি": "Khata-Kalam Business Academy",
  "তাসলিমা বিউটি একাডেমি": "Taslima Beauty Academy",
  "সাব্বির ক্রিকেট একাডেমি": "Sabbir Cricket Academy",
  "নুসরাত গণিত পাঠশালা": "Nusrat Maths Pathshala",
  "চার বন্ধুর একাডেমি — কোড, ডিজাইন, সার্ভার, এআই আর যন্ত্র। প্রতি সপ্তাহে লাইভে একটা জিনিস শূন্য থেকে বানিয়ে দেখান, আপনিও সাথে বানান।": "An academy of four friends — code, design, servers, AI and machines. Every week they build one thing from scratch live, and you build along.",
  "একজন স্থপতির একক একাডেমি — বন্যা আর ঝড়ের দেশে কম খরচে টেকসই বাড়ি আঁকা, পাঁচজনের ছোট ব্যাচে।": "One architect's solo academy — drawing low-cost, lasting houses for a land of floods and storms, in small batches of five.",
  "আঠারো বছরের গ্যারেজ এখন শ্রেণিকক্ষ — একজন মেকানিক, পাঁচজন শিক্ষার্থী, প্রতিটা স্ক্রু নিজের হাতে।": "An eighteen-year-old garage is now a classroom — one mechanic, five learners, every screw by your own hand.",
  "ঘরের রাঁধুনি আর ফুচকার গাড়ির মালিক মিলে — বিয়েবাড়ির ডেকচি থেকে রাস্তার খাবারের ব্যবসা।": "A home cook and a fuchka-cart owner together — from the big pots of a wedding to a street-food business.",
  "একজন গায়িকার একক একাডেমি — হাসন রাজা আর লালনের গান, প্রতি সপ্তাহে লাইভে গেয়ে শোনান, সরাসরি শুধরে দেন।": "One singer's solo academy — the songs of Hasan Raja and Lalon, sung live every week and corrected on the spot.",
  "একজন গিটারিস্টের একক একাডেমি — পাঁচজনের ব্যাচে প্রতিটা আঙুলের ভুল ধরে ইলেকট্রিক গিটার শেখানো।": "One guitarist's solo academy — electric guitar in batches of five, with every finger's mistake caught.",
  "একজন চিত্রশিল্পীর একক স্টুডিও — জলরং, বাংলা হরফ আর নিজের আঁকা ছবি বিক্রি করা।": "One painter's solo studio — watercolour, Bangla lettering and selling your own paintings.",
  "জামালপুরের কাঁথা শিল্পী আর রূপগঞ্জের জামদানি তাঁতি মিলে — ফোঁড় থেকে তাঁত, তারপর বাজার।": "A kantha artist from Jamalpur and a jamdani weaver from Rupganj together — from stitch to loom, then the market.",
  "তিন বন্ধু — ভিডিও, ফটো আর ডিজাইন। ফোন দিয়েই শুরু, শেষে নিজের চ্যানেল আর ক্লায়েন্ট।": "Three friends — video, photo and design. Start with just a phone; end with your own channel and clients.",
  "হিসাবের ছাত্র আর মুদি দোকানি মিলে — খাতা থেকে আয়কর, দোকান থেকে হোম ডেলিভারি।": "An accounting student and a grocer together — from the ledger to income tax, from the shop to home delivery.",
  "একজন মেহেদি শিল্পীর একক একাডেমি — বিয়ে আর উৎসবের সাজ, ত্বকের নিরাপত্তা আর সেবার ন্যায্য দাম।": "One henna artist's solo academy — wedding and festival looks, skin safety and a fair price for service.",
  "সাবেক বিভাগীয় খেলোয়াড়ের একক একাডেমি — রাজশাহীর মাঠে পাঁচজনের ব্যাচ, সব বয়সের জন্য।": "A former divisional player's solo academy — batches of five on the Rajshahi field, for every age.",
  "একজন গণিত শিক্ষকের একক পাঠশালা — রিকশা, বাজার আর ফসল দিয়ে অঙ্ক, ভয় ছাড়া।": "One maths teacher's solo pathshala — numbers through rickshaws, markets and crops, without fear.",

  // Departments
  "ওয়েব ডেভেলপমেন্ট": "Web development",
  "মেকাট্রনিক্স ও আইওটি": "Mechatronics & IoT",
  "স্থাপত্য নকশা": "Architectural design",
  "যানবাহন মেরামত": "Vehicle repair",
  "রান্না ও শেফ": "Cooking & chef",
  "কণ্ঠসংগীত": "Vocal music",
  "মিউজিক": "Music",
  "চিত্রকলা": "Fine art",
  "নকশিকাঁথা ও তাঁত": "Nakshi kantha & loom",
  "কনটেন্ট ক্রিয়েশন": "Content creation",
  "হিসাব ও ব্যবসা": "Accounts & business",
  "মেহেদি ও সাজ": "Henna & beauty",
  "ক্রিকেট ও ফিটনেস": "Cricket & fitness",
  "গণিত": "Mathematics",
  "ওয়েবসাইট আর ওয়েব অ্যাপ — পাতা বানানো থেকে ডেটাবেস, লগইন আর এআই চ্যাটবট পর্যন্ত।": "Websites and web apps — from building pages to databases, login and AI chatbots.",
  "সেন্সর, মোটর আর কোড একসাথে — গ্রামের সমস্যার যন্ত্র নিজের হাতে বানানো।": "Sensors, motors and code together — building machines for village problems with your own hands.",
  "বন্যা আর ঝড় মাথায় রেখে কম খরচের বাড়ির নকশা — অটোক্যাড থেকে মাঠের মাপজোখ।": "Low-cost house design with floods and storms in mind — from AutoCAD to field measurement.",
  "বাইক, রিকশা আর ইজিবাইক — ভিডিওতে বুঝুন, গ্যারেজে এসে নিজের হাতে খুলুন-জোড়া লাগান।": "Bikes, rickshaws and easy-bikes — understand on video, then come to the garage and take them apart and put them together yourself.",
  "ঘরের রান্নাঘর থেকে বিয়েবাড়ির ডেকচি — মাপ, পরিচ্ছন্নতা, খরচের হিসাব আর পরিবেশন।": "From the home kitchen to the wedding's big pots — measures, cleanliness, costing and serving.",
  "কণ্ঠ, সুর আর লোকগীতি — রেওয়াজ থেকে নিজের গান রেকর্ড করা পর্যন্ত।": "Voice, melody and folk songs — from practice to recording your own song.",
  "ইলেকট্রিক গিটার — প্রথম কর্ড থেকে ব্যান্ডে বাজানো আর লিড সোলো।": "Electric guitar — from the first chord to playing in a band and lead solos.",
  "জলরঙে নদী-গ্রাম, বাংলা হরফের ক্যালিগ্রাফি — আঁকা ছবি বিক্রি পর্যন্ত।": "Rivers and villages in watercolour, Bangla calligraphy — all the way to selling your paintings.",
  "জামালপুরের কাঁথা আর রূপগঞ্জের জামদানি — ফোঁড় থেকে বাজারে বিক্রি।": "Kantha of Jamalpur and jamdani of Rupganj — from stitch to selling in the market.",
  "ইউটিউবার হওয়া, প্রোডাক্ট ফটোগ্রাফি, মডেলিং আর গ্রাফিক ডিজাইন — ফোন দিয়েই শুরু।": "Becoming a YouTuber, product photography, modelling and graphic design — start with just a phone.",
  "দোকানের খাতা থেকে আয়কর রিটার্ন — টাকার হিসাব যে রাখে, ব্যবসা সে-ই টেকায়।": "From the shop ledger to the income tax return — whoever keeps the money's account keeps the business alive.",
  "বিয়ে আর উৎসবের মেহেদি নকশা, ত্বকের নিরাপত্তা, বাসায় গিয়ে সেবার দাম ঠিক করা।": "Henna designs for weddings and festivals, skin safety, and pricing a home visit.",
  "সব বয়সের জন্য — ব্যাটিং-বোলিংয়ের কৌশল, চোট এড়ানো, নিজের দল গড়া।": "For every age — batting and bowling technique, avoiding injury, building your own team.",
  "রিকশার গতি, বাজারের হিসাব, ফসলের মাপ — চারপাশের জিনিস দিয়ে গণিত।": "A rickshaw's speed, the market's sums, the measure of a crop — maths from the things around you.",

  // Courses
  "ওয়েব অ্যাপ বানানো — শূন্য থেকে লাইভ": "Building a web app — from zero to live",
  "ব্যাকএন্ড ও ডেটাবেস — অর্ডার নেওয়ার অ্যাপ": "Backend and database — an order-taking app",
  "ওয়েবে এআই — বাংলা চ্যাটবট": "AI on the web — a Bangla chatbot",
  "মেকাট্রনিক্স: সেন্সর থেকে রোবট": "Mechatronics: from sensors to robots",
  "আইওটি — ফোন থেকে খামার দেখা": "IoT — watching the farm from your phone",
  "সোলার পাম্প ও স্মার্ট সেচ": "Solar pumps and smart irrigation",
  "বন্যা-সহনশীল বাড়ির নকশা": "Designing flood-resilient houses",
  "অটোক্যাডে বাড়ির প্ল্যান — শুরু থেকে": "House plans in AutoCAD — from the start",
  "ঝড়-সহনশীল ঘর ও আশ্রয়কেন্দ্রের নকশা": "Designing storm-resilient homes and shelters",
  "মোটরসাইকেল সার্ভিসিং": "Motorcycle servicing",
  "ইঞ্জিন ও কার্বুরেটর ওভারহল": "Engine and carburettor overhaul",
  "রিকশা-ভ্যান মেরামত ও ইজিবাইকের ব্যাটারি": "Rickshaw-van repair and easy-bike batteries",
  "ঘরোয়া রান্না থেকে পেশাদার শেফ": "From home cooking to professional chef",
  "স্ট্রিট ফুড ব্যবসা — ফুচকা থেকে টিফিন": "Street-food business — from fuchka to tiffin",
  "বিয়েবাড়ির বড় রান্না — ১০০ থেকে ৫০০ জন": "Wedding-scale cooking — 100 to 500 guests",
  "কণ্ঠসংগীত ও সুর": "Vocal music and melody",
  "লোকগীতি — হাসন রাজা থেকে লালন": "Folk songs — from Hasan Raja to Lalon",
  "রেকর্ডিং ও নিজের গান প্রকাশ": "Recording and releasing your own song",
  "ইলেকট্রিক গিটার — শুরু থেকে": "Electric guitar — from the start",
  "কর্ড, রিদম আর ব্যান্ডে বাজানো": "Chords, rhythm and playing in a band",
  "লিড গিটার ও সোলো": "Lead guitar and solos",
  "জলরং — নদী, গ্রাম, আলো": "Watercolour — river, village, light",
  "বাংলা ক্যালিগ্রাফি": "Bangla calligraphy",
  "ছবি বিক্রি — প্রদর্শনী থেকে অনলাইন": "Selling paintings — from exhibition to online",
  "নকশিকাঁথা ও দর্জির কাজ": "Nakshi kantha and tailoring",
  "জামদানি তাঁতের হাতেখড়ি": "First steps in jamdani weaving",
  "দর্জির কাজ ও অনলাইনে বিক্রি": "Tailoring and selling online",
  "ইউটিউবার হওয়া — ভিডিও বানানো থেকে আয়": "Becoming a YouTuber — from making videos to earning",
  "প্রোডাক্ট ফটোগ্রাফি ও মডেলিং": "Product photography and modelling",
  "গ্রাফিক ডিজাইন ও ফেসবুক বিজ্ঞাপন": "Graphic design and Facebook ads",
  "এক্সেল, হিসাব ও আয়কর রিটার্ন": "Excel, accounts and income tax returns",
  "ছোট দোকান চালানো ও হোম ডেলিভারি": "Running a small shop and home delivery",
  "ব্যবসার লাইসেন্স, ভ্যাট ও লোন": "Business licence, VAT and loans",
  "মেহেদি নকশা — বিয়ে ও উৎসব": "Henna designs — weddings and festivals",
  "বিয়ের সাজ — মেকআপের হাতেখড়ি": "Bridal look — first steps in make-up",
  "ঘরে গিয়ে সেবা — দাম, বুকিং আর নিরাপত্তা": "Home-visit service — pricing, booking and safety",
  "ক্রিকেট কোচিং — সব বয়সে": "Cricket coaching — for every age",
  "ফিটনেস ও চোট এড়ানো": "Fitness and avoiding injury",
  "ফাস্ট বোলিং — গতি আর নিয়ন্ত্রণ": "Fast bowling — pace and control",
  "রিকশার গতি দিয়ে ক্যালকুলাস": "Calculus through a rickshaw's speed",
  "বাজারের হিসাবে পাটিগণিত ও বীজগণিত": "Arithmetic and algebra through the market's sums",
  "পরিসংখ্যান — বৃষ্টি আর ফসলের ডেটা": "Statistics — rain and crop data",
};
