/**
 * Wikimedia Commons photographs for the story page — generated by the
 * build script from reviewed picks; every file is CC BY / CC BY-SA /
 * CC0 / public domain, stored locally in /public/bangladesh, and shown
 * with this credit. Do not add a photo here without its credit.
 */

import type { Photo } from "./bangladesh";

export const commonsPhotos: Partial<Record<string, Photo>> = {
  sundarbans: {
    src: "/bangladesh/sundarbans.jpg",
    alt: "সুন্দরবনের ম্যানগ্রোভ বনের সারি, সামনে নদী",
    credit: { author: "Kingshuk Mondal", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Dense_Mangrove_Forest_of_the_Sundarban_Tiger_Reserve_during_High_Tide,_West_Bengal,_India_03.jpg" },
  },
  coxsbazar: {
    src: "/bangladesh/coxsbazar.jpg",
    alt: "কক্সবাজার সৈকতে সূর্যাস্ত, ভেজা বালিতে মানুষের প্রতিচ্ছবি",
    credit: { author: "Tanweer Morshed", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Cox%27s_Bazar_sea_beach_01.jpg" },
  },
  stmartin: {
    src: "/bangladesh/stmartin.jpg",
    alt: "সেন্ট মার্টিন দ্বীপে নারকেল গাছ, ফুল আর নীল সমুদ্র",
    credit: { author: "Niaz morshed Shovon", license: "Public domain", licenseUrl: "", sourceUrl: "https://commons.wikimedia.org/wiki/File:Saint_Martin%27s_Island.JPG" },
  },
  bandarban: {
    src: "/bangladesh/bandarban.jpg",
    alt: "বান্দরবানের কুয়াশাঢাকা সবুজ পাহাড়",
    credit: { author: "Syed Sajidul Islam", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:View_of_Nilachal_hill_after_rain,_Bandarban_(2).jpg" },
  },
  sajek: {
    src: "/bangladesh/sajek.jpg",
    alt: "সাজেকের পাহাড়চূড়া থেকে সূর্যাস্ত",
    credit: { author: "Rocky Masum", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Sunrise_at_Sajek_Valley.jpg" },
  },
  kaptai: {
    src: "/bangladesh/kaptai.jpg",
    alt: "পাহাড়ে ঘেরা রাঙামাটির কাপ্তাই হ্রদ",
    credit: { author: "Anica Tabassum", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Kaptai_lake,Rangamati,Bamgladesh.jpg" },
  },
  teagarden: {
    src: "/bangladesh/teagarden.jpg",
    alt: "শ্রীমঙ্গলের চা-বাগানের সারি আর ছায়াবৃক্ষ",
    credit: { author: "Kritzolina", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Tea_gardens_in_Sreemangal_11.jpg" },
  },
  ratargul: {
    src: "/bangladesh/ratargul.jpg",
    alt: "রাতারগুল জলাবনের ভেতর দিয়ে নৌকা",
    credit: { author: "Abdulmominbd (derivative: Aristeas)", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Ratargul_785_retouched.jpg" },
  },
  haor: {
    src: "/bangladesh/haor.jpg",
    alt: "টাঙ্গুয়ার হাওরের বিস্তীর্ণ জলে একটি নৌকা",
    credit: { author: "Ahnaf Tahmid Manan", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Tanguar_Haor_Houseboat.jpg" },
  },
  jaflong: {
    src: "/bangladesh/jaflong.jpg",
    alt: "জাফলংয়ের পাথুরে নদী আর সবুজ পাহাড়",
    credit: { author: "Derived Constant", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Jaflong,_Sylhet_(2025).jpg" },
  },
  river: {
    src: "/bangladesh/river.jpg",
    alt: "নদীতে পালতোলা নৌকা বাইছেন এক মাঝি",
    credit: { author: "joiseyshowaa", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Boat_Sailing_up_Padma_River_Bangladesh.jpg" },
  },
  village: {
    src: "/bangladesh/village.jpg",
    alt: "সবুজ ধানক্ষেতের মাঝ দিয়ে এঁকেবেঁকে যাওয়া আলপথ, দূরে গ্রাম",
    credit: { author: "Ramim Hosain", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Rural_Paddy_Field_Path_Bangladesh.jpg" },
  },
  mustard: {
    src: "/bangladesh/mustard.jpg",
    alt: "দিগন্তজোড়া হলুদ সরিষা ক্ষেতে সূর্যাস্ত",
    credit: { author: "Atashee", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Sunset_over_mustard_field.jpg" },
  },
  monsoon: {
    src: "/bangladesh/monsoon.jpg",
    alt: "বর্ষার বৃষ্টিতে ঝাপসা গাছপালা",
    credit: { author: "Mayeenul Islam", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Rain_in_rainy_season_in_Bangladesh.jpg" },
  },
  kashful: {
    src: "/bangladesh/kashful.jpg",
    alt: "নদীর ধারে সাদা কাশফুলের বন",
    credit: { author: "Auyon", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Kash_phul_at_Padma.jpg" },
  },
  winterfog: {
    src: "/bangladesh/winterfog.jpg",
    alt: "শীতের কুয়াশাভরা ভোরে খেজুর গাছের পেছনে সূর্যোদয়",
    credit: { author: "Abdul Momin", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:A_foggy_winter_morning.jpg" },
  },
  shimul: {
    src: "/bangladesh/shimul.jpg",
    alt: "বসন্তে লাল শিমুল ফুলে ভরা ডাল",
    credit: { author: "Saad Faruque", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Bombax_ceiba_-_Cotton_Tree_-_Shimul_Flower.jpg" },
  },
  shaheedminar: {
    src: "/bangladesh/shaheedminar.jpg",
    alt: "ঢাকার কেন্দ্রীয় শহীদ মিনার",
    credit: { author: "Biswarup Ganguly", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Central_Shaheed_Minar_-_Dhaka_Medical_College_Campus_-_Dhaka_2015-05-31_2577.JPG" },
  },
  smritisoudho: {
    src: "/bangladesh/smritisoudho.jpg",
    alt: "সাভারের জাতীয় স্মৃতিসৌধ, চারপাশে সবুজ",
    credit: { author: "Shirin Kona", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Jatiyo_Smriti_Soudho_left_view_(01).jpg" },
  },
  paharpur: {
    src: "/bangladesh/paharpur.jpg",
    alt: "পাহাড়পুরের সোমপুর মহাবিহারের ধ্বংসাবশেষ",
    credit: { author: "Khan-Tanvir", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Ruins_of_Bhuddist_Bihara_-_Somapura_Mahavihara.jpg" },
  },
  sixtydome: {
    src: "/bangladesh/sixtydome.jpg",
    alt: "বাগেরহাটের ষাট গম্বুজ মসজিদ",
    credit: { author: "Anup Sadi", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Sixty_Dome_Mosque_at_Bagerhat_(5).jpg" },
  },
  lalbagh: {
    src: "/bangladesh/lalbagh.jpg",
    alt: "ঢাকার লালবাগ কেল্লা ও বাগান",
    credit: { author: "Shmunmun", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Lalbagh_Kella_(Lalbagh_Fort)_Dhaka_Bangladesh_2011_36.JPG" },
  },
  ahsanmanzil: {
    src: "/bangladesh/ahsanmanzil.jpg",
    alt: "বুড়িগঙ্গার তীরে গোলাপি আহসান মঞ্জিল",
    credit: { author: "Mahbub Hossain Shaheed (mahosha)", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Ahsan_Manzil-Front_View.jpg" },
  },
  mahasthan: {
    src: "/bangladesh/mahasthan.jpg",
    alt: "বগুড়ার মহাস্থানগড়ের প্রাচীন প্রাচীর",
    credit: { author: "P.K. Niyogi (edit: GreenComputer)", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", sourceUrl: "https://commons.wikimedia.org/wiki/File:BD_Mahasthangarh1_without_people.jpg" },
  },
  padmabridge: {
    src: "/bangladesh/padmabridge.jpg",
    alt: "নদীর উপর দিয়ে বিস্তৃত পদ্মা সেতু",
    credit: { author: "Azim Khan Ronnie", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:The_padma_bridge_02.jpg" },
  },
  boishakh: {
    src: "/bangladesh/boishakh.jpg",
    alt: "পহেলা বৈশাখের শোভাযাত্রায় বিশাল রঙিন মুখোশ-ভাস্কর্য",
    credit: { author: "NahidSultan", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Mongol_Shobhajatra,_Pohela_Boishakh_(25).jpg" },
  },
  rickshaw: {
    src: "/bangladesh/rickshaw.jpg",
    alt: "ঢাকার রঙিন রিকশাচিত্রে সাজানো রিকশা",
    credit: { author: "Francisco Anzola", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Rickshaws_(253699803).jpeg" },
  },
  surrender1971: {
    src: "/bangladesh/surrender1971.jpg",
    alt: "১৯৭১ সালের আত্মসমর্পণের দৃশ্য নিয়ে নির্মিত ভাস্কর্য",
    credit: { author: "Shsourav", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Statue_representing_the_signing_of_the_Pakistani_Instrument_of_Surrender_at_the_Mujibnagar_Memorial_Monument_and_Complex.jpg" },
  },
  tagore: {
    src: "/bangladesh/tagore.jpg",
    alt: "রবীন্দ্রনাথ ঠাকুরের প্রতিকৃতি",
    focus: "50% 25%",
    credit: { author: "Unknown author", license: "Public domain", licenseUrl: "", sourceUrl: "https://commons.wikimedia.org/wiki/File:Rabindranath_Tagore.jpg" },
  },
  nazrul: {
    src: "/bangladesh/nazrul.jpg",
    alt: "বাঁশি হাতে কাজী নজরুল ইসলাম",
    focus: "50% 20%",
    credit: { author: "Unknown photographer", license: "Public domain", licenseUrl: "", sourceUrl: "https://commons.wikimedia.org/wiki/File:Nazrul.jpg" },
  },
  lalon: {
    src: "/bangladesh/lalon.jpg",
    alt: "জ্যোতিরিন্দ্রনাথ ঠাকুরের আঁকা লালন সাঁইয়ের স্কেচ (১৮৮৯)",
    focus: "50% 30%",
    credit: { author: "Jyotirindranath Tagore", license: "Public domain", licenseUrl: "", sourceUrl: "https://commons.wikimedia.org/wiki/File:Fakir_Lalon_Shah.jpg" },
  },
  jibanananda: {
    src: "/bangladesh/jibanananda.jpg",
    alt: "জীবনানন্দ দাশের প্রতিকৃতি",
    focus: "50% 30%",
    credit: { author: "Unknown author", license: "Public domain", licenseUrl: "", sourceUrl: "https://commons.wikimedia.org/wiki/File:Jibanananda_Das_Old.jpg" },
  },
  rokeya: {
    src: "/bangladesh/rokeya.jpg",
    alt: "বেগম রোকেয়ার প্রতিকৃতি",
    focus: "50% 25%",
    credit: { author: "Unknown author", license: "Public domain", licenseUrl: "", sourceUrl: "https://commons.wikimedia.org/wiki/File:Begum_Rokeya.jpg" },
  },
  jcbose: {
    src: "/bangladesh/jcbose.jpg",
    alt: "জগদীশচন্দ্র বসু",
    focus: "50% 25%",
    credit: { author: "The Birth Centenary Committee, printed by P.C. Ray", license: "Public domain", licenseUrl: "", sourceUrl: "https://commons.wikimedia.org/wiki/File:J.C.Bose.JPG" },
  },
  snbose: {
    src: "/bangladesh/snbose.jpg",
    alt: "সত্যেন্দ্রনাথ বসুর প্রতিকৃতি",
    focus: "50% 25%",
    credit: { author: "Unknown author", license: "Public domain", licenseUrl: "", sourceUrl: "https://commons.wikimedia.org/wiki/File:SatyenBose1925.jpg" },
  },
  jasimuddin: {
    src: "/bangladesh/jasimuddin.jpg",
    alt: "পল্লীকবি জসীমউদ্‌দীনের প্রতিকৃতি",
    focus: "50% 25%",
    credit: { author: "Jennifer A. Cutting, Library of Congress", license: "Public domain", licenseUrl: "", sourceUrl: "https://commons.wikimedia.org/wiki/File:Jasimuddin_Lomax_1951_(2).jpg" },
  },
  mahasthan_b: {
    src: "/bangladesh/mahasthan_b.jpg",
    alt: "মহাস্থানগড়ের প্রাচীন দুর্গপ্রাচীর ও ঢিবি",
    credit: { author: "Zaheed Sarwer Khan", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:View_of_Mahasthangarh.jpg" },
  },
  mahasthan_c: {
    src: "/bangladesh/mahasthan_c.jpg",
    alt: "মহাস্থানগড়ে খননে উন্মোচিত ইটের কাঠামো",
    credit: { author: "Zaheed Sarwer Khan", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Walls_of_Mahasthangarh.jpg" },
  },
  paharpur_b: {
    src: "/bangladesh/paharpur_b.jpg",
    alt: "আকাশ থেকে সোমপুর মহাবিহারের ক্রুশাকার নকশা",
    credit: { author: "Md. Ahsanul Haque Nayem", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Aerial_view_of_Somapura_Mahavihara.jpg" },
  },
  paharpur_c: {
    src: "/bangladesh/paharpur_c.jpg",
    alt: "গোধূলিতে পাহাড়পুর বিহারের অবয়ব",
    credit: { author: "Rangan Datta Wiki", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Somapura_Mahavihara_2024_39.jpg" },
  },
  sixtydome_b: {
    src: "/bangladesh/sixtydome_b.jpg",
    alt: "গাছের ছায়ায় ষাট গম্বুজ মসজিদ",
    credit: { author: "Belayet (User:Bellayet)", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Shat_Gombuj_Mosque_0016.JPG" },
  },
  sixtydome_c: {
    src: "/bangladesh/sixtydome_c.jpg",
    alt: "তালগাছের সারির পেছনে ষাট গম্বুজ মসজিদ",
    credit: { author: "Anup Sadi", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Sixty_Dome_Mosque_at_Bagerhat_(7).jpg" },
  },
  lalbagh_b: {
    src: "/bangladesh/lalbagh_b.jpg",
    alt: "লালবাগ কেল্লার প্রাচীর",
    credit: { author: "Shmunmun", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Lalbagh_Kella_(Lalbagh_Fort)_Dhaka_Bangladesh_2011_15.JPG" },
  },
  ahsanmanzil_b: {
    src: "/bangladesh/ahsanmanzil_b.jpg",
    alt: "সবুজ চত্বর থেকে আহসান মঞ্জিল",
    credit: { author: "Lahsim Niasoh", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Ahsan_Manzil_Building_23577.jpg" },
  },
  ahsanmanzil_c: {
    src: "/bangladesh/ahsanmanzil_c.jpg",
    alt: "পুরান ঢাকার ভবনের মাঝে আহসান মঞ্জিল",
    credit: { author: "Shafiul Islam Shaikot", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Historic_Ahsan_Manzil_Palace_Bangladesh.jpg" },
  },
  shaheedminar_b: {
    src: "/bangladesh/shaheedminar_b.jpg",
    alt: "কেন্দ্রীয় শহীদ মিনারের চত্বর",
    credit: { author: "Biswarup Ganguly", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Central_Shaheed_Minar_-_Dhaka_Medical_College_Campus_-_Dhaka_2015-05-31_2585.JPG" },
  },
  smritisoudho_b: {
    src: "/bangladesh/smritisoudho_b.jpg",
    alt: "আকাশ থেকে জাতীয় স্মৃতিসৌধ প্রাঙ্গণ ও জলাশয়",
    credit: { author: "Azim Khan Ronnie", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Aerial_photographs_of_Jatiyo_Smriti_Soudho_DJI_0065-1.jpg" },
  },
};
